<?php

/**
 * Nom du template pour le menu utilisateur.
 * les differentes valeurs sont dans Stephane888\HtmlBootstrap\SuggestionsMenus::Suggestions_menu__account()
 */
const TEMPLATE_menu__account = 'menu__account_icon';

/**
 * En mode developpment cette varaible est à true, cela permet de charger les differentes feuilles de style et scripts.
 *
 * @var string
 */
const LOAD_SCSS_BY_SESSION = true;

/**
 * template utlisé par le menu principal.
 * les differentes valeurs sont dans Stephane888\HtmlBootstrap\SuggestionsMenus::Suggestions_menu__main()
 */
const TEMPLATE_menu__main = 'menu__main_full';